# Base compose for all services required by TLRL. By default it's runs on the default network
# named tlrl.
---
version: '3.7'
networks:
  default:
    external: false
    name: tlrl

services:
  solr:
    image: solr:8.5.1
    container_name: solr
    restart: "no"
    volumes:
      - "./target/solr:/var/solr"
      - "./config/solr/tlrl/conf:/var/solr/data/tlrl/conf"
      - "./config/solr/tlrl/core.properties:/var/solr/data/tlrl/core.properties"
      - "./target/solr/data/tlrl/data:/var/solr/data/tlrl/data"
    ports:
      - "8983:8983"

  zookeeper:
    image: bitnami/zookeeper:3
    container_name: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - './target/zookeeper:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2
    container_name: kafka
    volumes:
      - './target/kafka:/bitnami/kafka'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    ports:
      - '9092:9092'
      - '9093:9093'
    depends_on:
      - 'zookeeper'

  postgres:
    image: postgres:12.3-alpine
    container_name: postgres
    restart: "no"
    environment:
      - DB_NAME=${DB_NAME:-tlrldb}
      - DB_ADMIN=${DB_ADMIN:-tlrladmin}
      - DB_USER=${DB_USER:-tlrluser}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD:-tlrladmin}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD:-tlrluser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - "./backend/db/schema:/docker-entrypoint-initdb.d"
      - "./target/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  fetcher:
    build:
      context: ./fetcher
    image: tlrl-fetcher
    container_name: tlrl-fetcher
    environment:
      - FETCHER_LOG_LVL=${FETCHER_LOG_LVL:-4}
      - FETCHER_KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
      - FETCHER_SOLR_SERVER=${SOLR_SERVER:-solr:8983}
    volumes:
      - "${FETCHER_HOST_ARCHIVE_DIR:-./target/fetcher/archive}:/data/fetcher/archive"
    depends_on:
      - 'kafka'

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: "no"
    volumes:
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "${FETCHER_HOST_ARCHIVE_DIR:-./target/fetcher/archive}:/data/fetcher/archive"
    ports:
      - "9080:9080"

  app:
    build:
      context: .
      args:
        - SKIP_TESTS=${SKIP_TESTS:-true}
        - TARGET_DB=${TARGET_DB:-h2}
        - SPRING_PROFILES=${SPRING_PROFILES:-dev}
    image: tlrl-app
    container_name: tlrl-app
    environment:
      - TARGET_DB=${TARGET_DB:-h2}
      - SPRING_PROFILES=${SPRING_PROFILES:-dev}
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
      - SOLR_SERVER=${SOLR_SERVER:-solr:8983}
    ports:
      - "8080:8080"
    depends_on:
      - 'kafka'
